import { createClient } from '@/utils/supabase/server';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
    apiVersion: '2025-01-27.acacia' as any,
});

export const SUBSCRIPTION_QUOTAS = {
    free: { tokens: 10000, priceId: null, requiredFlxStake: 0 },
    pro: { tokens: 1000000, priceId: process.env.STRIPE_PRO_PRICE_ID, requiredFlxStake: 1000 },
    enterprise: { tokens: -1, priceId: process.env.STRIPE_ENTERPRISE_PRICE_ID, requiredFlxStake: 10000 },
};

export const SUPPORTED_ASSETS = ['BTC', 'ETH', 'BNB', 'USDT'];
const ASSET_PRICES = {
    'BTC': 65000,
    'ETH': 3500,
    'BNB': 600,
    'USDT': 1.0,
    'FLX': 0.10
};

// Islamic: Profit sharing/Yield rates for staking
const STAKING_YIELD_RATES = {
    'BTC': 0.05, // 5% annual equivalent to FLX credits
    'ETH': 0.04,
    'BNB': 0.06,
    'USDT': 0.03
};

/**
 * Determine subscription tier from a Stripe price ID
 */
export function determineTier(priceId: string): 'pro' | 'enterprise' | 'free' {
    if (priceId === process.env.STRIPE_PRO_PRICE_ID) return 'pro';
    if (priceId === process.env.STRIPE_ENTERPRISE_PRICE_ID) return 'enterprise';
    return 'free';
}

export async function getUserSubscription(userId: string) {
    const supabase = await createClient();
    const { data, error } = await supabase
        .from('subscriptions')
        .select('*')
        .eq('user_id', userId)
        .single();

    if (error && error.code !== 'PGRST116') throw error;
    return data;
}

export async function checkQuota(userId: string, tokensRequested: number) {
    const supabase = await createClient();
    const sub = await getUserSubscription(userId);
    const tier = sub?.tier || 'free';
    const limit = SUBSCRIPTION_QUOTAS[tier as keyof typeof SUBSCRIPTION_QUOTAS].tokens;

    if (limit === -1) return true; // Unlimited

    const { data: quota } = await supabase
        .from('user_usage_quotas')
        .select('token_usage_current')
        .eq('user_id', userId)
        .eq('month_year', new Date().toISOString().slice(0, 7) + '-01')
        .single();

    const current = quota?.token_usage_current || 0;
    return (current + tokensRequested) <= limit;
}

export async function createCheckoutSession(userId: string, tier: 'pro' | 'enterprise') {
    const sub = await getUserSubscription(userId);
    const priceId = SUBSCRIPTION_QUOTAS[tier].priceId;

    if (!priceId) {
        throw new Error(`No Stripe price ID configured for tier: ${tier}`);
    }

    // Create or reuse Stripe customer
    let customerId = sub?.stripe_customer_id;
    if (!customerId) {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        const customer = await stripe.customers.create({
            email: user?.email || undefined,
            metadata: { supabase_user_id: userId },
        });
        customerId = customer.id;
    }

    const session = await stripe.checkout.sessions.create({
        customer: customerId,
        payment_method_types: ['card'],
        line_items: [{ price: priceId, quantity: 1 }],
        mode: 'subscription',
        success_url: `${process.env.NEXT_PUBLIC_APP_URL}/billing?success=true`,
        cancel_url: `${process.env.NEXT_PUBLIC_APP_URL}/billing?canceled=true`,
        metadata: { userId, tier },
    });

    return session;
}

/**
 * Calculate total FLX credit generated by user's staked assets
 */
export async function calculateStakingFlxCredit(userId: string): Promise<number> {
    const supabase = await createClient();
    const { data: stakes, error } = await supabase
        .from('staked_assets')
        .select('*')
        .eq('user_id', userId)
        .eq('is_active', true);

    if (error || !stakes) return 0;

    let totalFlxCredit = 0;
    for (const stake of stakes) {
        const asset = stake.asset_type as keyof typeof ASSET_PRICES;
        const priceUsd = ASSET_PRICES[asset] || 0;
        const yieldRate = STAKING_YIELD_RATES[asset as keyof typeof STAKING_YIELD_RATES] || 0;

        // Value in USD
        const valueUsd = stake.amount * priceUsd;
        // FLX Equivalent (based on current FLX price)
        const flxEquivalent = valueUsd / ASSET_PRICES['FLX'];

        // The "Payment" is effectively the yield/rent on the capital
        // Islamic: Asset remains user's property, they pay using the generated gain/utility
        totalFlxCredit += flxEquivalent * yieldRate;
    }

    return totalFlxCredit;
}

export async function getStakedAssets(userId: string) {
    const supabase = await createClient();
    const { data: stakes } = await supabase
        .from('staked_assets')
        .select('*')
        .eq('user_id', userId)
        .eq('is_active', true);
    return stakes || [];
}

/**
 * Record a new staking event
 * Uses Service Role to bypass RLS as this is a system action.
 */
export async function recordStakingEvent(userId: string, asset: string, amount: number) {
    // Direct import to avoid circular dep or using the auth-scoped client
    const { createClient } = require('@supabase/supabase-js');

    // Use Service Role Key to bypass RLS
    const supabaseAdmin = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.SUPABASE_SERVICE_ROLE_KEY!,
        {
            auth: {
                autoRefreshToken: false,
                persistSession: false
            }
        }
    );

    const assetKey = asset.toUpperCase() as keyof typeof ASSET_PRICES;

    const { error } = await supabaseAdmin
        .from('staked_assets')
        .insert({
            user_id: userId,
            asset_type: assetKey,
            amount: amount,
            entry_price_usd: ASSET_PRICES[assetKey] || 0,
            is_active: true
        });

    if (error) throw error;

    // Automatically check and upgrade tier if sufficient
    await refreshSubscriptionFromStaking(userId);
}

export async function refreshSubscriptionFromStaking(userId: string) {
    const flxCredit = await calculateStakingFlxCredit(userId);
    let tier: 'enterprise' | 'pro' | 'free' = 'free';

    if (flxCredit >= SUBSCRIPTION_QUOTAS.enterprise.requiredFlxStake) tier = 'enterprise';
    else if (flxCredit >= SUBSCRIPTION_QUOTAS.pro.requiredFlxStake) tier = 'pro';

    const supabase = await createClient();
    await supabase
        .from('subscriptions')
        .upsert({
            user_id: userId,
            tier: tier,
            payment_method: 'staking',
            status: 'active',
            updated_at: new Date().toISOString()
        }, { onConflict: 'user_id' });

    await initializeMonthlyQuota(userId, tier);
}

/**
 * Initialize or reset monthly quota for a user based on their tier
 */
export async function initializeMonthlyQuota(userId: string, tier: string) {
    const supabase = await createClient();

    // If it's a "free" tier, check if user has staking that qualifies them for higher
    let finalTier = tier;
    if (tier === 'free') {
        const stakes = await calculateStakingFlxCredit(userId);
        if (stakes >= SUBSCRIPTION_QUOTAS.enterprise.requiredFlxStake) finalTier = 'enterprise';
        else if (stakes >= SUBSCRIPTION_QUOTAS.pro.requiredFlxStake) finalTier = 'pro';
    }

    const limit = SUBSCRIPTION_QUOTAS[finalTier as keyof typeof SUBSCRIPTION_QUOTAS]?.tokens || 10000;
    const currentMonth = new Date().toISOString().slice(0, 7) + '-01';

    await supabase
        .from('user_usage_quotas')
        .upsert({
            user_id: userId,
            month_year: currentMonth,
            token_usage_limit: limit === -1 ? 999999999 : limit,
            token_usage_current: 0,
        }, { onConflict: 'user_id,month_year' });
}

export { stripe };
