import { createClient } from '@/utils/supabase/server';
import Stripe from 'stripe';
import { getTierConfig, TierConfig } from './economics';
import { getUserStakingProfile, depositStake } from './staking';
import { CONTRACTS } from '@/lib/blockchain/contracts';
import { getProvider } from '@/lib/blockchain/provider';
import { ethers } from 'ethers';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
    apiVersion: '2025-01-27.acacia' as any,
});

if (!process.env.STRIPE_PRO_PRICE_ID || !process.env.STRIPE_ENTERPRISE_PRICE_ID) {
    console.warn("Missing Stripe Price IDs in environment variables. Billing may malfunction.");
}

export const SUBSCRIPTION_QUOTAS = {
    free: { ...getTierConfig('free'), priceId: null, tokens: getTierConfig('free').flaLimit },
    pro: { ...getTierConfig('pro'), priceId: process.env.STRIPE_PRO_PRICE_ID, tokens: getTierConfig('pro').flaLimit },
    enterprise: { ...getTierConfig('enterprise'), priceId: process.env.STRIPE_ENTERPRISE_PRICE_ID, tokens: getTierConfig('enterprise').flaLimit },
};

export const SUPPORTED_ASSETS = ['BTC', 'ETH', 'BNB', 'USDT'];

/**
 * Determine subscription tier from a Stripe price ID
 */
export function determineTier(priceId: string): 'pro' | 'enterprise' | 'free' {
    if (priceId === process.env.STRIPE_PRO_PRICE_ID) return 'pro';
    if (priceId === process.env.STRIPE_ENTERPRISE_PRICE_ID) return 'enterprise';
    return 'free';
}

export async function getUserSubscription(userId: string) {
    const { createAdminClient } = await import('@/utils/supabase/server');
    const supabase = await createAdminClient();
    const { data, error } = await supabase
        .from('subscriptions')
        .select('*')
        .eq('user_id', userId)
        .single();

    if (error && error.code !== 'PGRST116') throw error;
    return data;
}

export async function checkQuota(userId: string, tokensRequested: number) {
    const { createAdminClient } = await import('@/utils/supabase/server');
    const supabase = await createAdminClient();
    const sub = await getUserSubscription(userId);
    const tier = sub?.tier || 'free';
    const limit = SUBSCRIPTION_QUOTAS[tier as keyof typeof SUBSCRIPTION_QUOTAS].tokens;

    if (limit === -1) return true; // Unlimited

    const { data: quota } = await supabase
        .from('user_usage_quotas')
        .select('token_usage_current')
        .eq('user_id', userId)
        .eq('month_year', new Date().toISOString().slice(0, 7) + '-01')
        .single();

    const current = quota?.token_usage_current || 0;
    return (current + tokensRequested) <= limit;
}

export async function createCheckoutSession(userId: string, tier: 'pro' | 'enterprise') {
    const sub = await getUserSubscription(userId);
    const priceId = SUBSCRIPTION_QUOTAS[tier].priceId;

    if (!priceId) {
        throw new Error(`No Stripe price ID configured for tier: ${tier}. Check your .env file.`);
    }

    // Create or reuse Stripe customer
    let customerId = sub?.stripe_customer_id;
    if (!customerId) {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        const customer = await stripe.customers.create({
            email: user?.email || undefined,
            metadata: { supabase_user_id: userId },
        });
        customerId = customer.id;
    }

    const session = await stripe.checkout.sessions.create({
        customer: customerId,
        payment_method_types: ['card'],
        line_items: [{ price: priceId, quantity: 1 }],
        mode: 'subscription',
        success_url: `${process.env.NEXT_PUBLIC_APP_URL}/billing?success=true`,
        cancel_url: `${process.env.NEXT_PUBLIC_APP_URL}/billing?canceled=true`,
        metadata: { userId, tier },
    });

    return session;
}

/**
 * Calculate total FLX credit generated by user's staked assets
 * Uses Real-time Price Oracle via Staking Service.
 */
export async function calculateStakingFlxCredit(userId: string): Promise<number> {
    const profile = await getUserStakingProfile(userId);
    return profile.totalStakingPower;
}

export async function getStakedAssets(userId: string) {
    const profile = await getUserStakingProfile(userId);
    return profile.positions;
}

/**
 * Record a new staking event
 * Uses Service Role to bypass RLS as this is a system action.
 */
export async function recordStakingEvent(userId: string, asset: string, amount: number) {
    await depositStake(userId, asset, amount);

    // Automatically check and upgrade tier if sufficient
    await refreshSubscriptionFromStaking(userId);
}

export async function refreshSubscriptionFromStaking(userId: string) {
    const fs = require('fs');
    const log = (msg: string) => { try { fs.appendFileSync('debug.log', `[BillingService] ${msg}\n`); } catch { } };

    const flxCredit = await calculateStakingFlxCredit(userId);
    let tier: 'enterprise' | 'pro' | 'free' = 'free';

    if (flxCredit >= SUBSCRIPTION_QUOTAS.enterprise.requiredFlxStake) tier = 'enterprise';
    else if (flxCredit >= SUBSCRIPTION_QUOTAS.pro.requiredFlxStake) tier = 'pro';

    const { createAdminClient } = await import('@/utils/supabase/server');
    const supabase = await createAdminClient();
    const { error } = await supabase
        .from('subscriptions')
        .upsert({
            user_id: userId,
            tier: tier,
            payment_method: 'staking',
            status: 'active',
            updated_at: new Date().toISOString()
        }, { onConflict: 'user_id' });

    if (error) {
        // console.error(`Error updating subscription: ${error.message}`); // Replaced log with console.error for visibility
    } else {
        // console.log(`Successfully updated subscription to ${tier}`); // Replaced log with console.log for visibility
    }

    await initializeMonthlyQuota(userId, tier);
}

/**
 * Initialize or reset monthly quota for a user based on their tier
 */
export async function initializeMonthlyQuota(userId: string, tier: string) {
    const { createAdminClient } = await import('@/utils/supabase/server');
    const supabase = await createAdminClient();

    // If it's a "free" tier, check if user has staking that qualifies them for higher
    let finalTier = tier;
    if (tier === 'free') {
        const stakes = await calculateStakingFlxCredit(userId);
        if (stakes >= SUBSCRIPTION_QUOTAS.enterprise.requiredFlxStake) finalTier = 'enterprise';
        else if (stakes >= SUBSCRIPTION_QUOTAS.pro.requiredFlxStake) finalTier = 'pro';
    }

    const limit = SUBSCRIPTION_QUOTAS[finalTier as keyof typeof SUBSCRIPTION_QUOTAS]?.tokens || 10000;
    const currentMonth = new Date().toISOString().slice(0, 7) + '-01';

    await supabase
        .from('user_usage_quotas')
        .upsert({
            user_id: userId,
            month_year: currentMonth,
            token_usage_limit: limit === -1 ? 999999999 : limit,
            token_usage_current: 0,
        }, { onConflict: 'user_id,month_year' });
}

/**
 * Admin: Get global billing and economic statistics
 */
export async function getAdminBillingStats(scopeUserId?: string) {
    const { createAdminClient } = await import('@/utils/supabase/server');
    const supabase = await createAdminClient();

    // 1. Total Staked Power
    let stakesQuery = supabase
        .from('staked_assets')
        .select('amount, asset_type, entry_price_usd')
        .eq('is_active', true);

    if (scopeUserId) {
        stakesQuery = stakesQuery.eq('user_id', scopeUserId);
    }

    const { data: stakes } = await stakesQuery;

    // Unified calculation for the admin view using Oracle prices
    const { getAssetPrices } = await import('./oracle');
    const prices = await getAssetPrices();
    const LIQUIDITY_POWER_MULTIPLIER = 10;

    let totalPower = 0;
    stakes?.forEach(s => {
        const asset = s.asset_type;
        const price = prices[asset] || 0;
        const valueUsd = s.amount * price;

        let power = 0;
        if (asset === 'FLX') {
            power = s.amount;
        } else {
            power = valueUsd * LIQUIDITY_POWER_MULTIPLIER;
        }
        totalPower += power;
    });

    // 2. Tier Distribution
    let subsQuery = supabase
        .from('subscriptions')
        .select('tier');

    if (scopeUserId) {
        subsQuery = subsQuery.eq('user_id', scopeUserId);
    }

    const { data: subs } = await subsQuery;

    const distribution = {
        free: subs?.filter(s => s.tier === 'free').length || 0,
        pro: subs?.filter(s => s.tier === 'pro').length || 0,
        enterprise: subs?.filter(s => s.tier === 'enterprise').length || 0,
    };

    // 3. Active Users (using quotas as proxy for activity this month)
    const currentMonth = new Date().toISOString().slice(0, 7) + '-01';
    let activityQuery = supabase
        .from('user_usage_quotas')
        .select('*', { count: 'exact', head: true })
        .eq('month_year', currentMonth);

    if (scopeUserId) {
        activityQuery = activityQuery.eq('user_id', scopeUserId);
    }

    const { count: activeUsers } = await activityQuery;

    return {
        totalPower,
        distribution,
        activeUsers: activeUsers || 0,
        timestamp: new Date().toISOString()
    };
}

/**
 * Admin: Get list of users with billing context
 */
export async function getAdminUsers(limit = 50, offset = 0, scopeUserId?: string) {
    const { createAdminClient } = await import('@/utils/supabase/server');
    const supabase = await createAdminClient();

    let query = supabase
        .from('subscriptions')
        .select(`
            user_id,
            tier,
            status,
            payment_method,
            updated_at
        `)
        .order('updated_at', { ascending: false })
        .range(offset, offset + limit - 1);

    if (scopeUserId) {
        query = query.eq('user_id', scopeUserId);
    }

    const { data: subs, error } = await query;
    if (error) throw error;
    if (!subs || subs.length === 0) return [];

    // Manual Join for Quotas due to lack of direct FK
    const userIds = subs.map(s => s.user_id);
    const currentMonth = new Date().toISOString().slice(0, 7) + '-01';

    const { data: quotas } = await supabase
        .from('user_usage_quotas')
        .select('user_id, token_usage_current, token_usage_limit')
        .in('user_id', userIds)
        .eq('month_year', currentMonth);

    // Merge Data
    return subs.map(sub => {
        const quota = quotas?.find(q => q.user_id === sub.user_id);
        return {
            ...sub,
            user_usage_quotas: quota ? {
                token_usage_current: quota.token_usage_current,
                token_usage_limit: quota.token_usage_limit
            } : null
        };
    });
}

/**
 * Fetch Sovereign AI Dimension rewards (FLA) for a wallet
 */
export async function getSovereignRewards(walletAddress: string) {
    try {
        const provider = getProvider();

        // 1. FLA Balance (Liquid)
        const flxToken = new ethers.Contract(CONTRACTS.saiToken.address, CONTRACTS.saiToken.abi, provider);
        const balanceWei = await flxToken.balanceOf(walletAddress);
        const flaBalance = parseFloat(ethers.formatEther(balanceWei));

        // 2. Miner Stats (Lifetime Earnings)
        const aiDim = new ethers.Contract(CONTRACTS.aiDimension.address, CONTRACTS.aiDimension.abi, provider);
        const stats = await aiDim.miners(walletAddress);

        return {
            flaBalance,
            lifetimeFlaEarned: parseFloat(ethers.formatEther(stats.totalFlaEarned)),
            tasksCompleted: Number(stats.totalTasksCompleted),
            aiReputation: Number(stats.aiReputation)
        };
    } catch (error) {
        console.error("Error fetching Sovereign Rewards:", error);
        return {
            flaBalance: 0,
            lifetimeFlaEarned: 0,
            tasksCompleted: 0,
            aiReputation: 0
        };
    }
}

/**
 * Fetch Sovereign Revenue Hub rewards (ETH Share) for a wallet
 */
export async function getRevenueRewards(walletAddress: string) {
    try {
        const provider = getProvider();
        const profitPool = new ethers.Contract(CONTRACTS.profitPool.address, CONTRACTS.profitPool.abi, provider);

        const [pendingWei, totalClaimedWei, accruedWei] = await Promise.all([
            profitPool.pendingReward(walletAddress),
            profitPool.totalClaimed(walletAddress),
            profitPool.accruedRewards(walletAddress)
        ]);

        return {
            claimableEth: parseFloat(ethers.formatEther(pendingWei)),
            totalLifetimeClaimed: parseFloat(ethers.formatEther(totalClaimedWei)),
            accruedRewards: parseFloat(ethers.formatEther(accruedWei))
        };
    } catch (error) {
        console.error("Error fetching Revenue Rewards:", error);
        return {
            claimableEth: 0,
            totalLifetimeClaimed: 0,
            accruedRewards: 0
        };
    }
}

export { stripe };
