version: '3.8'

services:
  db:
    container_name: flexia-supabase-db
    image: supabase/postgres:15.1.0.117
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    container_name: flexia-supabase-auth
    image: supabase/gotrue:v2.132.3
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9999:9999"
    environment:
      GOTRUE_DB_DATABASE_URL: ${GOTRUE_DB_DATABASE_URL}
      GOTRUE_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      GOTRUE_SITE_URL: ${GOTRUE_SITE_URL}
      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${GOTRUE_EXTERNAL_EMAIL_ENABLED}
      GOTRUE_DB_MAX_POOL_SIZE: 20
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${GOTRUE_API_EXTERNAL_URL}
      GOTRUE_DB_DRIVER: ${GOTRUE_DB_DRIVER}

  rest:
    container_name: flexia-supabase-rest
    image: postgrest/postgrest:v11.2.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS}
      PGRST_DB_ANON_ROLE: anon

  kong:
    container_name: flexia-supabase-kong
    image: kong:2.8.1
    depends_on:
      auth:
        condition: service_started
      rest:
        condition: service_started
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/var/lib/kong/kong.yml
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
